### ISSUE TITLE
Unused methods of BaseFilters class

### ISSUE THREAD

**Issue by osule** [mykeels/laravel-filters#1]
First, this was a nice piece of work shared with the community.
I wanted to learn whether there was a road to documenting the usage of the following methods of the `BaseFilters` class.

- [::defer](https://github.com/mykeels/laravel-filters/blob/master/src/BaseFilters.php#L44)
- [::transform](https://github.com/mykeels/laravel-filters/blob/master/src/BaseFilters.php#L50)
- [::add](https://github.com/mykeels/laravel-filters/blob/master/src/BaseFilters.php#L57)

All three methods aren't currently invoked and I'm assuming if they're necessary to conform to an interface for the dynamic scope applied on the model.

I noticed that the only methods invoked through`BaseFilters` are the constructor, the `::apply` and `::filters` ones.

`BaseFilters::apply` is the only one invoked directly from the trait.
What do you think about providing an interface for this? 
_I'm guessing that there isn't much value in an interface for `BaseFilters::apply` than for `BaseFilters::filters`_.

**Comment by mykeels** [comment]
Yo! Check the "Defer loading relationships" section of [“Writing even better Eloquent Filters 🎉”](https://medium.com/@mykeels/writing-even-better-eloquent-filters-ee23ab24a49c)

I need to update the README.md to reflect this ... Could you help with this?

**Comment by mykeels** [comment]
@osule can you confirm that that blog post gives the information you seek?

**Comment by osule** [comment]
Yes @mykeels! That was helpful to clarify the need for all three functions.

I will like to suggest that all three of them be factored into a trait. 
Reason for this is that they present a more cohesive unit that way and the reason for their addition is much more obvious.

I'll set out to do a PR that documents the three later today and maybe add some tests along the way.

**Comment by mykeels** [comment]
Yaaay ... Thanks for the PR in advance, so cool! 💃

I'm not sure about refactoring those three methods into a separate trait since they're only used in the BaseFilter class. Perhaps as the project grows, there might be reason to?
