### ISSUE TITLE
Feature request: Allow for optional extra filters to the filter scope

### ISSUE THREAD

**Issue by orobogenius** [mykeels/laravel-filters#3]
I have to first commend the package, great work.

I wanted to apply filters to my models but these filters were not necessarily being gotten from the current request's query strings. I wanted to be able to specify extra filters directly from my code without depending on these filters being set from the request.

Currently, there's no conventional way to do this. I could in practice, do either of the following to achieve this:

**Modifying the Request**
I could modify the current request and then add the filters by merging the extra filters into the current request:
  ```php
  $request->merge(['sort' => '-created_at']);
 ```
But I wouldn't want the filters to be dependent on the request, if I did, I would have just added them directly in the URL. 

**Dynamically add to globals**
I could also dynamically add the extra filters to the filters object by calling the `add()` method:
```php
//Controller: UserFilters $filters
$users = $this->service->repo()->getAllResource($filters, ['sort' => '-created_at', 'age' => 21]);

//Repository: UserFilters $filters, $extraFilters
if ($extraFilters) {
     foreach ($extraFilters as $filter => $value) {
       $filters->add($filter, $value);
     }
}
```
The issue with this is, it's adding the extra filters as globals and this would have an undesired effect in future calls to the `filter` scope because the added filters would now be applied as globals on subsequent filter queries. I assumed that the `$globals` property was by design, meant to contain filters that would always be applied when filtering a model.

## Suggestion
Allow the `filter` scope to accept extra filters that would be applied to the query (alongside request filters and globals) as a one-off. This would make extra filters work independent from request filters and globals and won't have the undesired effect globals present. With this, one can now do this without having to add the extra filters to globals or modifying the request:

```php
//Controller: UserFilters $filters
$adultUsers = $this->service->repo()->getAllResource($filters, ['sort' => '-created_at', 'age' => 18]);

$allUsers = $this->service->repo()->getAllResource($filters);
```

I've prepared a PR #4 should it be approved.

**Comment by mykeels** [comment]
@orobogenius there's already an `add(...)` method which does this, so you can add extra _(already defined)_ filters by their name and value with `$filters->add($name, $value);`.

Is this what you seek?

If so, the README has to be updated to reflect this.

**Comment by orobogenius** [comment]
That's not what I seek @mykeels. I know there's already an `add(...)` method but it has two issues at present:

1. It doesn't accept an array of filters
2. **It adds the filter to globals which would then be treated as global filters and be applied on subsequent calls to the filter scope even when you don't want them to.**

The idea is to be able to apply one-off filters *(already defined)* that would be applied once and won't be applied as globals for each successive filter operation.

**Comment by mykeels** [comment]
I see what you mean now @orobogenius ... I think this package definitely needs this feature. 

I'm reviewing the PR right now.
